name: food_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.4+7

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flare_splash_screen: ^4.0.0
  flutter_custom_clippers: ^2.0.0
  percent_indicator: ^4.2.2
  shared_preferences: ^2.1.1
  logging: ^1.1.1
  dio: ^5.1.2
  scrollable_positioned_list: ^0.3.8
  rxdart: ^0.27.4
  fluttertoast: ^8.0.8
  flutter_spinkit: ^5.2.0
  firebase_auth: ^4.6.1
  permission_handler: ^10.0.0

  google_sign_in: ^6.1.1
  google_maps_flutter: ^2.1.6
  flutter_login_facebook: ^1.4.1
  #google_maps_place_picker: ^1.0.1
  firebase_core: ^2.13.0
  geolocator: ^9.0.2
  location: ^4.4.0
  uuid: ^3.0.5
  #  paytm: ^1.0.8
  #upi_india: ^3.0.1
  webview_flutter: ^3.0.0
  scrollable_clean_calendar: ^1.0.1
  http: ^0.13.4
  pin_code_fields: ^7.3.0
  flutter_polyline_points: ^1.0.0
  google_maps_place_picker_mb: ^3.0.2
  another_xlider: ^3.0.1
  geocoding: ^2.1.0
  razorpay_flutter: ^1.3.5
  lottie: ^2.6.0
#  hive: ^2.2.3
  flutter_svg: ^1.1.6
#  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
#  hive_generator: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  analyzer: ^5.13.0
  path_provider: ^2.0.10
  uri_to_file: ^0.2.0
  provider: ^6.0.3
  get: ^4.6.5
  _fe_analyzer_shared: ^61.0.0
  url_launcher: ^6.1.11
  # flutter_google_places: ^0.3.0
  google_api_headers: ^1.3.0
  google_maps_webservice: ^0.0.19
  google_place: ^0.4.7
  timelines: ^0.1.0
  syncfusion_flutter_sliders: ^22.2.12
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  pinput: ^2.2.31
  vs_scrollbar: ^0.2.1
  hexcolor: ^3.0.1
  syncfusion_flutter_datepicker: ^22.2.12
  dotted_border: ^2.0.0+3
  flutter_rating_bar: ^4.0.1
  connectivity_plus: ^3.0.2
  confetti: ^0.7.0
  package_info_plus_web: ^2.0.0
  text_scroll: ^0.2.0
  otp_autofill: ^3.0.0
#  share_plus: ^7.0.0
  flutter_google_places_hoc081098: ^1.2.0
  easy_debounce: ^2.0.3
  easy_search_bar: ^2.5.0
  google_fonts: ^4.0.3
  dots_indicator: ^3.0.0
  device_preview: ^1.1.0
  scroll_to_index: ^3.0.1
  shimmer: ^3.0.0
  video_player: ^2.7.1
  logger: ^2.0.2
  spring: ^2.0.2
  timer_count_down: ^2.2.2
  speech_to_text: ^6.3.0
  flutter_switch: ^0.3.2
  share_plus: ^7.1.0
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1


#  material_scrollbar: ^0.0.1









dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_applogo.png"
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/icons/bottom_nav_bar_icons/
    - assets/lotties/
    - assets/images/background.png
    - assets/images/heart_fill.svg
    - assets/images/heart_outline.svg
    - assets/video/splash_video.mp4
    - assets/video/pass_change.gif
    - assets/food.json
  fonts:
    - family: productsans_bold
      fonts:
        - asset: assets/font/productsans_bold.ttf
    - family: productsans_regular
      fonts:
        - asset: assets/font/productsans_regular.ttf
    - family: CustomIcon
      fonts:
        - asset: assets/font/CustomIcon.ttf
